## This file configures the scheduler used to change the Gym environment during the training process

training_network_files:
  - configs/networks/Compuserve_n14_e17/Compuserve-in4-cap1.graphml
  - configs/networks/node6/node6-in2-cap1-delay10.graphml
  - configs/networks/Claranet_n15_e18/Claranet-in4-cap1.graphml
#  - configs/networks/bteurope/bteurope-in4-cap1.graphml
#  - configs/networks/abilene/abilene-in4-rand-cap0-2.graphml
#  - configs/networks/abilene/abilene-in4-rand-cap1-2-perm2.graphml
#  - configs/networks/abilene/abilene-in4-cap3.graphml
#  - configs/networks/abilene/abilene-in4-rand-cap.graphml
#  - configs/networks/abilene/abilene-in4-rand-cap0-5.graphml
  

inference_network: configs/networks/abilene/abilene-in4-rand-cap1-2.graphml

period: 10