# module for configuring the simulator
# configuration parameters are loaded and used both when using the simulator via the CLI and via the interface
# all parameters are required, defaults are in comments

inter_arrival_mean: 10.0           # default: 10.0
deterministic_arrival: True
flow_dr_mean: 1.0                  # default: 1.0
flow_dr_stdev: 0.0                 # default: 0.0
flow_size_shape: 0.001               # default: 0.001
deterministic_size: True
run_duration: 100                  # default: 100

ttl_choices: [100]

write_flow_actions: True
write_schedule: True

### This parameter overwrites links' capacity
force_link_cap: 3

### This parameter overwrites nodes' capacity
# force_node_cap: [1, 4] 